// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StowCrate.Infrastructure.Persistence.ConfigDb;

#nullable disable

namespace StowCrate.Infrastructure.Persistence.ConfigDb.Migrations
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20260903161305_AddRelocationCleanupV6")]
    partial class AddRelocationCleanupV6
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.ArchiveVersionEntity", b =>
                {
                    b.Property<byte[]>("ArchiveVersionId")
                        .HasColumnType("BLOB");

                    b.Property<string>("ArchiveFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ArchiveSpecFingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ArchiveUnitId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("IntegritySha256")
                        .HasColumnType("BLOB");

                    b.Property<long?>("Length")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PlanId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long?>("PublishedAtUtcMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("ArchiveVersionId");

                    b.ToTable("ArchiveVersion", null, t =>
                        {
                            t.HasCheckConstraint("CK_ArchiveVersion_Digests", "length(ArchiveSpecFingerprint)=32 AND (IntegritySha256 IS NULL OR length(IntegritySha256)=32)");

                            t.HasCheckConstraint("CK_ArchiveVersion_Format", "ArchiveFormat IN ('SEVEN_ZIP','ZIP','TAR_ZSTD')");

                            t.HasCheckConstraint("CK_ArchiveVersion_Ids", "length(ArchiveVersionId)=16 AND length(PlanId)=16 AND length(ArchiveUnitId)=16");

                            t.HasCheckConstraint("CK_ArchiveVersion_Lifecycle", "Lifecycle IN ('PREPARED','VERIFIED','PUBLISHED','SUPERSEDED')");

                            t.HasCheckConstraint("CK_ArchiveVersion_Metadata", "(Lifecycle='PREPARED' AND IntegritySha256 IS NULL AND Length IS NULL AND PublishedAtUtcMs IS NULL) OR (Lifecycle='VERIFIED' AND IntegritySha256 IS NOT NULL AND Length>=0 AND PublishedAtUtcMs IS NULL) OR (Lifecycle IN ('PUBLISHED','SUPERSEDED') AND IntegritySha256 IS NOT NULL AND Length>=0 AND PublishedAtUtcMs IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.CommittedArchiveUnitBaselineEntity", b =>
                {
                    b.Property<byte[]>("PlanId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ArchiveUnitId")
                        .HasColumnType("BLOB");

                    b.Property<long>("ArchiveSemanticsVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ArchiveSpecFingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ArchiveVersionId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("BoundaryComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("CompressionComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("EntrySetFingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ExternalMappingComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("FingerprintEncodingVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("FormatComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("LinkPolicyComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ManifestComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("OutputPathEncodingVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProtectionComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RulesComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("RulesSemanticsVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SelectionFingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("PlanId", "ArchiveUnitId");

                    b.HasIndex("PlanId", "ArchiveUnitId", "ArchiveVersionId");

                    b.ToTable("CommittedArchiveUnitBaseline", null, t =>
                        {
                            t.HasCheckConstraint("CK_Baseline_Digests", "length(EntrySetFingerprint)=32 AND length(SelectionFingerprint)=32 AND length(ArchiveSpecFingerprint)=32 AND length(RulesComponent)=32 AND length(BoundaryComponent)=32 AND length(LinkPolicyComponent)=32 AND length(ExternalMappingComponent)=32 AND length(FormatComponent)=32 AND length(CompressionComponent)=32 AND length(ProtectionComponent)=32 AND length(ManifestComponent)=32");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.CommittedOutputLayoutStateEntity", b =>
                {
                    b.Property<byte[]>("PlanId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ArchiveUnitId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("OutputLayoutFingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("PlanId", "ArchiveUnitId");

                    b.ToTable("CommittedOutputLayoutState", null, t =>
                        {
                            t.HasCheckConstraint("CK_OutputLayout_Digest", "length(OutputLayoutFingerprint)=32");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.CurrentVersionEntity", b =>
                {
                    b.Property<byte[]>("PlanId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ArchiveUnitId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ArchiveVersionId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("CurrentRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId", "ArchiveUnitId");

                    b.HasIndex("ArchiveVersionId")
                        .IsUnique();

                    b.HasIndex("PlanId", "ArchiveUnitId", "ArchiveVersionId");

                    b.ToTable("CurrentVersion", (string)null);
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.DatabaseMetadataEntity", b =>
                {
                    b.Property<long>("SingletonKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("DatabaseId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("DeviceId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.HasKey("SingletonKey");

                    b.HasIndex("DatabaseId")
                        .IsUnique();

                    b.ToTable("DatabaseMetadata", null, t =>
                        {
                            t.HasCheckConstraint("CK_DatabaseMetadata_Ids", "length(DatabaseId)=16 AND length(DeviceId)=16");

                            t.HasCheckConstraint("CK_DatabaseMetadata_SchemaVersion", "SchemaVersion > 0");

                            t.HasCheckConstraint("CK_DatabaseMetadata_Singleton", "SingletonKey = 1");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.ExternalLocalBindingEntity", b =>
                {
                    b.Property<byte[]>("PlanId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ExternalSourceId")
                        .HasColumnType("BLOB");

                    b.Property<string>("CanonicalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComparisonKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanId", "ExternalSourceId");

                    b.ToTable("ExternalLocalBinding", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExternalLocalBinding_Active", "IsActive IN (0,1)");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.FileManagedArchiveUnitRegistrationEntity", b =>
                {
                    b.Property<byte[]>("PlanId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ArchiveUnitId")
                        .HasColumnType("BLOB");

                    b.Property<string>("IdentityOrigin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogicalUnitPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SourceId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("PlanId", "ArchiveUnitId");

                    b.HasIndex("PlanId", "SourceId", "LogicalUnitPath")
                        .IsUnique();

                    b.ToTable("FileManagedArchiveUnitRegistration", null, t =>
                        {
                            t.HasCheckConstraint("CK_FileManagedRegistration_Active", "IsActive IN (0,1)");

                            t.HasCheckConstraint("CK_FileManagedRegistration_Ids", "length(PlanId)=16 AND length(SourceId)=16 AND length(ArchiveUnitId)=16");

                            t.HasCheckConstraint("CK_FileManagedRegistration_Origin", "IdentityOrigin IN ('DIRECTIVE','LOCAL_REGISTRATION')");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.HistoryVersionPlacementEntity", b =>
                {
                    b.Property<byte[]>("ArchiveVersionId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ArchiveUnitId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("HistoryRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PlanId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("ArchiveVersionId");

                    b.HasIndex("PlanId", "HistoryRelativePath")
                        .IsUnique();

                    b.HasIndex("PlanId", "ArchiveUnitId", "ArchiveVersionId");

                    b.ToTable("HistoryVersionPlacement", (string)null);
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.MaintenanceStateEntity", b =>
                {
                    b.Property<long>("MaintenanceStateRowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ArchiveUnitId")
                        .HasColumnType("BLOB");

                    b.Property<string>("Detail")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("PlanId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtcMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("MaintenanceStateRowId");

                    b.HasIndex("PlanId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("UX_MaintenanceState_PlanScope")
                        .HasFilter("ArchiveUnitId IS NULL");

                    b.HasIndex("PlanId", "ArchiveUnitId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("UX_MaintenanceState_UnitScope")
                        .HasFilter("ArchiveUnitId IS NOT NULL");

                    b.ToTable("MaintenanceState", null, t =>
                        {
                            t.HasCheckConstraint("CK_Maintenance_Kind", "Kind IN ('HISTORY_RETENTION','OLD_CURRENT_PATH_CLEANUP','STORAGE_RELOCATION','OUTPUT_REORGANIZATION','SCHEDULE_RECONCILIATION')");

                            t.HasCheckConstraint("CK_Maintenance_Status", "Status IN ('PENDING','OUT_OF_SYNC','COMPLETED')");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.ManagedPlanDocumentEntity", b =>
                {
                    b.Property<byte[]>("PlanId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("CanonicalUtf8Payload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PayloadSha256")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtcMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanId");

                    b.ToTable("ManagedPlanDocument", null, t =>
                        {
                            t.HasCheckConstraint("CK_ManagedPlanDocument_Digest", "length(PayloadSha256)=32");

                            t.HasCheckConstraint("CK_ManagedPlanDocument_Payload", "length(CanonicalUtf8Payload)>0");

                            t.HasCheckConstraint("CK_ManagedPlanDocument_Revision", "Revision > 0");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.OutputRootLocalBindingEntity", b =>
                {
                    b.Property<byte[]>("PlanId")
                        .HasColumnType("BLOB");

                    b.Property<string>("RootKind")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComparisonKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanId", "RootKind");

                    b.ToTable("OutputRootLocalBinding", null, t =>
                        {
                            t.HasCheckConstraint("CK_OutputRootLocalBinding_Active", "IsActive IN (0,1)");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.PlanRegistrationEntity", b =>
                {
                    b.Property<byte[]>("PlanId")
                        .HasColumnType("BLOB");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileDocumentPath")
                        .HasColumnType("TEXT");

                    b.Property<long>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RegisteredAtUtcMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanId");

                    b.ToTable("PlanRegistration", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlanRegistration_Active", "IsActive IN (0,1)");

                            t.HasCheckConstraint("CK_PlanRegistration_Authority", "(Authority='MANAGED' AND FileDocumentPath IS NULL) OR (Authority='FILE_BACKED' AND FileDocumentPath IS NOT NULL)");

                            t.HasCheckConstraint("CK_PlanRegistration_Id", "length(PlanId)=16");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.PublishIntentBaselineEntity", b =>
                {
                    b.Property<byte[]>("PlanId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ArchiveUnitId")
                        .HasColumnType("BLOB");

                    b.Property<long>("ArchiveSemanticsVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ArchiveSpecFingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("BoundaryComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("CompressionComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("EntrySetFingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ExecutionBindingFingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ExecutionSemanticFingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ExternalMappingComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("FingerprintEncodingVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("FormatComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("LinkPolicyComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ManifestComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("OutputLayoutFingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("OutputPathEncodingVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ProtectionComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RulesComponent")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("RulesSemanticsVersion")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SelectionFingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("PlanId", "ArchiveUnitId");

                    b.ToTable("PublishIntentBaseline", null, t =>
                        {
                            t.HasCheckConstraint("CK_PublishIntentBaseline_Digests", "length(EntrySetFingerprint)=32 AND length(SelectionFingerprint)=32 AND length(ArchiveSpecFingerprint)=32 AND length(RulesComponent)=32 AND length(BoundaryComponent)=32 AND length(LinkPolicyComponent)=32 AND length(ExternalMappingComponent)=32 AND length(FormatComponent)=32 AND length(CompressionComponent)=32 AND length(ProtectionComponent)=32 AND length(ManifestComponent)=32 AND length(OutputLayoutFingerprint)=32 AND length(ExecutionSemanticFingerprint)=32 AND length(ExecutionBindingFingerprint)=32");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.PublishIntentEntity", b =>
                {
                    b.Property<byte[]>("PlanId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ArchiveUnitId")
                        .HasColumnType("BLOB");

                    b.Property<long?>("CurrentPublishedAtUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrentRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ExpectedNewIntegritySha256")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("HistoryCaptureRequirement")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoryRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("HistoryVerifiedIntegritySha256")
                        .HasColumnType("BLOB");

                    b.Property<string>("NewArchiveFormat")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("NewArchiveSpecFingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("NewArchiveVersionId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("NewLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OldArchiveFormat")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("OldArchiveSpecFingerprint")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("OldArchiveVersionId")
                        .HasColumnType("BLOB");

                    b.Property<string>("OldCurrentRelativePath")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("OldIntegritySha256")
                        .HasColumnType("BLOB");

                    b.Property<long?>("OldLength")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("OldPublishedAtUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("OutputLayoutFingerprint")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlanId", "ArchiveUnitId");

                    b.HasIndex("NewArchiveVersionId")
                        .IsUnique();

                    b.ToTable("PublishIntent", null, t =>
                        {
                            t.HasCheckConstraint("CK_PublishIntent_Digests", "length(NewArchiveSpecFingerprint)=32 AND length(ExpectedNewIntegritySha256)=32 AND length(OutputLayoutFingerprint)=32 AND (OldArchiveSpecFingerprint IS NULL OR length(OldArchiveSpecFingerprint)=32) AND (OldIntegritySha256 IS NULL OR length(OldIntegritySha256)=32) AND (HistoryVerifiedIntegritySha256 IS NULL OR length(HistoryVerifiedIntegritySha256)=32)");

                            t.HasCheckConstraint("CK_PublishIntent_HistoryRequirement", "HistoryCaptureRequirement IN ('REQUIRED','NOT_REQUIRED','UNKNOWN_LEGACY')");

                            t.HasCheckConstraint("CK_PublishIntent_Ids", "length(PlanId)=16 AND length(ArchiveUnitId)=16 AND length(NewArchiveVersionId)=16 AND (OldArchiveVersionId IS NULL OR length(OldArchiveVersionId)=16)");

                            t.HasCheckConstraint("CK_PublishIntent_OldFacts", "(OldArchiveVersionId IS NULL AND OldArchiveFormat IS NULL AND OldArchiveSpecFingerprint IS NULL AND OldIntegritySha256 IS NULL AND OldLength IS NULL AND OldPublishedAtUtcMs IS NULL AND OldCurrentRelativePath IS NULL AND HistoryRelativePath IS NULL AND HistoryVerifiedIntegritySha256 IS NULL) OR (OldArchiveVersionId IS NOT NULL AND OldArchiveFormat IS NOT NULL AND OldArchiveSpecFingerprint IS NOT NULL AND OldIntegritySha256 IS NOT NULL AND OldLength>=0 AND OldPublishedAtUtcMs IS NOT NULL AND OldCurrentRelativePath IS NOT NULL)");

                            t.HasCheckConstraint("CK_PublishIntent_Stage", "Stage IN ('PREPARED','HISTORY_CAPTURED','CURRENT_PUBLISHED','METADATA_COMMITTED')");

                            t.HasCheckConstraint("CK_PublishIntent_StageFacts", "(Stage='PREPARED' AND CurrentPublishedAtUtcMs IS NULL AND HistoryRelativePath IS NULL AND HistoryVerifiedIntegritySha256 IS NULL) OR (Stage='HISTORY_CAPTURED' AND HistoryCaptureRequirement IN ('REQUIRED','UNKNOWN_LEGACY') AND CurrentPublishedAtUtcMs IS NULL AND OldArchiveVersionId IS NOT NULL AND HistoryRelativePath IS NOT NULL AND HistoryVerifiedIntegritySha256 IS NOT NULL) OR (Stage IN ('CURRENT_PUBLISHED','METADATA_COMMITTED') AND CurrentPublishedAtUtcMs IS NOT NULL AND ((HistoryCaptureRequirement='REQUIRED' AND OldArchiveVersionId IS NOT NULL AND HistoryRelativePath IS NOT NULL AND HistoryVerifiedIntegritySha256 IS NOT NULL) OR (HistoryCaptureRequirement='NOT_REQUIRED' AND HistoryRelativePath IS NULL AND HistoryVerifiedIntegritySha256 IS NULL) OR (HistoryCaptureRequirement='UNKNOWN_LEGACY' AND ((HistoryRelativePath IS NULL AND HistoryVerifiedIntegritySha256 IS NULL) OR (OldArchiveVersionId IS NOT NULL AND HistoryRelativePath IS NOT NULL AND HistoryVerifiedIntegritySha256 IS NOT NULL)))))");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.RetentionDeletionIntentEntity", b =>
                {
                    b.Property<byte[]>("ArchiveVersionId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ArchiveUnitId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long?>("CompletedAtUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ExpectedIntegritySha256")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("ExpectedLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HistoryRelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("KeepLastVersionsCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PlanId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("RetentionSemanticsVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SelectedAtUtcMs")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("SelectionId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ArchiveVersionId");

                    b.HasIndex("SelectionId");

                    b.HasIndex("PlanId", "ArchiveUnitId", "ArchiveVersionId");

                    b.ToTable("RetentionDeletionIntent", null, t =>
                        {
                            t.HasCheckConstraint("CK_RetentionDeletionIntent_Digest", "length(ExpectedIntegritySha256)=32");

                            t.HasCheckConstraint("CK_RetentionDeletionIntent_Facts", "ExpectedLength>=0 AND RetentionSemanticsVersion=1 AND KeepLastVersionsCount>=1 AND ((Stage='PREPARED' AND CompletedAtUtcMs IS NULL) OR (Stage='COMPLETED' AND CompletedAtUtcMs IS NOT NULL))");

                            t.HasCheckConstraint("CK_RetentionDeletionIntent_Ids", "length(ArchiveVersionId)=16 AND length(PlanId)=16 AND length(ArchiveUnitId)=16 AND length(SelectionId)=16");

                            t.HasCheckConstraint("CK_RetentionDeletionIntent_Stage", "Stage IN ('PREPARED','COMPLETED')");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.ScheduleInstallationEntity", b =>
                {
                    b.Property<byte[]>("PlanId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("DeviceId")
                        .HasColumnType("BLOB");

                    b.Property<string>("AdapterToken")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("InstalledIntentDigest")
                        .HasColumnType("BLOB");

                    b.Property<string>("LastError")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpaqueInstallationId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtcMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanId", "DeviceId");

                    b.ToTable("ScheduleInstallation", null, t =>
                        {
                            t.HasCheckConstraint("CK_Schedule_Digest", "InstalledIntentDigest IS NULL OR length(InstalledIntentDigest)=32");

                            t.HasCheckConstraint("CK_Schedule_Status", "Status IN ('NOT_INSTALLED','INSTALLED','OUT_OF_SYNC','ERROR')");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.SecretBindingEntity", b =>
                {
                    b.Property<byte[]>("PlanId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SecretSlotId")
                        .HasColumnType("BLOB");

                    b.Property<long>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpaqueReference")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("SecretRevision")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanId", "SecretSlotId");

                    b.ToTable("SecretBinding", null, t =>
                        {
                            t.HasCheckConstraint("CK_SecretBinding_Active", "IsActive IN (0,1)");

                            t.HasCheckConstraint("CK_SecretBinding_Revision", "SecretRevision > 0");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.SourceLocalBindingEntity", b =>
                {
                    b.Property<byte[]>("PlanId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SourceId")
                        .HasColumnType("BLOB");

                    b.Property<string>("CanonicalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComparisonKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("IsActive")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanId", "SourceId");

                    b.ToTable("SourceLocalBinding", null, t =>
                        {
                            t.HasCheckConstraint("CK_SourceLocalBinding_Active", "IsActive IN (0,1)");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.StorageRelocationIntentEntity", b =>
                {
                    b.Property<byte[]>("TransactionId")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ConfigurationPayload")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ConfigurationSha256")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("DeviceId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ManifestPayload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ManifestSha256")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PlanId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ProgressPayload")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("ProgressSha256")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long>("ProtocolVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId");

                    b.HasIndex("PlanId")
                        .IsUnique();

                    b.ToTable("StorageRelocationIntent", null, t =>
                        {
                            t.HasCheckConstraint("CK_Relocation_Configuration", "(ConfigurationPayload IS NULL AND ConfigurationSha256 IS NULL) OR (ConfigurationPayload IS NOT NULL AND ConfigurationSha256 IS NOT NULL AND length(ConfigurationPayload)>0 AND length(ConfigurationSha256)=32)");

                            t.HasCheckConstraint("CK_Relocation_Ids", "length(TransactionId)=16 AND length(PlanId)=16 AND length(DeviceId)=16");

                            t.HasCheckConstraint("CK_Relocation_Payload", "length(ManifestPayload)>0 AND length(ProgressPayload)>0 AND length(ManifestSha256)=32 AND length(ProgressSha256)=32");

                            t.HasCheckConstraint("CK_Relocation_Protocol", "ProtocolVersion=1 AND Revision>=1");

                            t.HasCheckConstraint("CK_Relocation_Stage", "Stage IN ('PREPARED','TARGETS_DURABLE','METADATA_COMMITTED','COMPLETED')");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.StorageRelocationRootReservationEntity", b =>
                {
                    b.Property<byte[]>("TransactionId")
                        .HasColumnType("BLOB");

                    b.Property<string>("Slot")
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComparisonKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TransactionId", "Slot");

                    b.ToTable("StorageRelocationRootReservation", null, t =>
                        {
                            t.HasCheckConstraint("CK_RelocationRoot_Path", "length(CanonicalPath)>0 AND length(ComparisonKey)>0");

                            t.HasCheckConstraint("CK_RelocationRoot_Slot", "Slot IN ('CURRENT_OLD','CURRENT_NEW','HISTORY_OLD','HISTORY_NEW')");
                        });
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.ArchiveVersionEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.PlanRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.CommittedArchiveUnitBaselineEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.ArchiveVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId", "ArchiveUnitId", "ArchiveVersionId")
                        .HasPrincipalKey("PlanId", "ArchiveUnitId", "ArchiveVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.CommittedOutputLayoutStateEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.PlanRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.CurrentVersionEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.ArchiveVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId", "ArchiveUnitId", "ArchiveVersionId")
                        .HasPrincipalKey("PlanId", "ArchiveUnitId", "ArchiveVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.ExternalLocalBindingEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.PlanRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.FileManagedArchiveUnitRegistrationEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.PlanRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.HistoryVersionPlacementEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.ArchiveVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId", "ArchiveUnitId", "ArchiveVersionId")
                        .HasPrincipalKey("PlanId", "ArchiveUnitId", "ArchiveVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.MaintenanceStateEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.PlanRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.ManagedPlanDocumentEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.PlanRegistrationEntity", null)
                        .WithOne()
                        .HasForeignKey("StowCrate.Infrastructure.Persistence.ConfigDb.ManagedPlanDocumentEntity", "PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.OutputRootLocalBindingEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.PlanRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.PublishIntentBaselineEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.PublishIntentEntity", null)
                        .WithOne()
                        .HasForeignKey("StowCrate.Infrastructure.Persistence.ConfigDb.PublishIntentBaselineEntity", "PlanId", "ArchiveUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.PublishIntentEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.PlanRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.RetentionDeletionIntentEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.ArchiveVersionEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId", "ArchiveUnitId", "ArchiveVersionId")
                        .HasPrincipalKey("PlanId", "ArchiveUnitId", "ArchiveVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.ScheduleInstallationEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.PlanRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.SecretBindingEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.PlanRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.SourceLocalBindingEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.PlanRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.StorageRelocationIntentEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.PlanRegistrationEntity", null)
                        .WithMany()
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("StowCrate.Infrastructure.Persistence.ConfigDb.StorageRelocationRootReservationEntity", b =>
                {
                    b.HasOne("StowCrate.Infrastructure.Persistence.ConfigDb.StorageRelocationIntentEntity", null)
                        .WithMany()
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
