using Microsoft.EntityFrameworkCore.Migrations;

// <auto-generated />
#nullable disable
#pragma warning disable IDE0161, CA1861

namespace StowCrate.Infrastructure.Persistence.ConfigDb.Migrations
{
    /// <inheritdoc />
    public partial class InitialConfigDbV1 : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "DatabaseMetadata",
                columns: table => new
                {
                    SingletonKey = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    SchemaVersion = table.Column<long>(type: "INTEGER", nullable: false),
                    DatabaseId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    DeviceId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    CreatedAtUtcMs = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_DatabaseMetadata", x => x.SingletonKey);
                    table.CheckConstraint("CK_DatabaseMetadata_Ids", "length(DatabaseId)=16 AND length(DeviceId)=16");
                    table.CheckConstraint("CK_DatabaseMetadata_SchemaVersion", "SchemaVersion > 0");
                    table.CheckConstraint("CK_DatabaseMetadata_Singleton", "SingletonKey = 1");
                });

            migrationBuilder.CreateTable(
                name: "PlanRegistration",
                columns: table => new
                {
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    Authority = table.Column<string>(type: "TEXT", nullable: false),
                    FileDocumentPath = table.Column<string>(type: "TEXT", nullable: true),
                    IsActive = table.Column<long>(type: "INTEGER", nullable: false),
                    RegisteredAtUtcMs = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PlanRegistration", x => x.PlanId);
                    table.CheckConstraint("CK_PlanRegistration_Active", "IsActive IN (0,1)");
                    table.CheckConstraint("CK_PlanRegistration_Authority", "(Authority='MANAGED' AND FileDocumentPath IS NULL) OR (Authority='FILE_BACKED' AND FileDocumentPath IS NOT NULL)");
                    table.CheckConstraint("CK_PlanRegistration_Id", "length(PlanId)=16");
                });

            migrationBuilder.CreateTable(
                name: "ArchiveVersion",
                columns: table => new
                {
                    ArchiveVersionId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveUnitId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveFormat = table.Column<string>(type: "TEXT", nullable: false),
                    ArchiveSpecFingerprint = table.Column<byte[]>(type: "BLOB", nullable: false),
                    Lifecycle = table.Column<string>(type: "TEXT", nullable: false),
                    IntegritySha256 = table.Column<byte[]>(type: "BLOB", nullable: true),
                    Length = table.Column<long>(type: "INTEGER", nullable: true),
                    PublishedAtUtcMs = table.Column<long>(type: "INTEGER", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ArchiveVersion", x => x.ArchiveVersionId);
                    table.UniqueConstraint("AK_ArchiveVersion_PlanId_ArchiveUnitId_ArchiveVersionId", x => new { x.PlanId, x.ArchiveUnitId, x.ArchiveVersionId });
                    table.CheckConstraint("CK_ArchiveVersion_Digests", "length(ArchiveSpecFingerprint)=32 AND (IntegritySha256 IS NULL OR length(IntegritySha256)=32)");
                    table.CheckConstraint("CK_ArchiveVersion_Format", "ArchiveFormat IN ('SEVEN_ZIP','ZIP','TAR_ZSTD')");
                    table.CheckConstraint("CK_ArchiveVersion_Ids", "length(ArchiveVersionId)=16 AND length(PlanId)=16 AND length(ArchiveUnitId)=16");
                    table.CheckConstraint("CK_ArchiveVersion_Lifecycle", "Lifecycle IN ('PREPARED','VERIFIED','PUBLISHED','SUPERSEDED')");
                    table.CheckConstraint("CK_ArchiveVersion_Metadata", "(Lifecycle='PREPARED' AND IntegritySha256 IS NULL AND Length IS NULL AND PublishedAtUtcMs IS NULL) OR (Lifecycle='VERIFIED' AND IntegritySha256 IS NOT NULL AND Length>=0 AND PublishedAtUtcMs IS NULL) OR (Lifecycle IN ('PUBLISHED','SUPERSEDED') AND IntegritySha256 IS NOT NULL AND Length>=0 AND PublishedAtUtcMs IS NOT NULL)");
                    table.ForeignKey(
                        name: "FK_ArchiveVersion_PlanRegistration_PlanId",
                        column: x => x.PlanId,
                        principalTable: "PlanRegistration",
                        principalColumn: "PlanId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "CommittedOutputLayoutState",
                columns: table => new
                {
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveUnitId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    OutputLayoutFingerprint = table.Column<byte[]>(type: "BLOB", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CommittedOutputLayoutState", x => new { x.PlanId, x.ArchiveUnitId });
                    table.CheckConstraint("CK_OutputLayout_Digest", "length(OutputLayoutFingerprint)=32");
                    table.ForeignKey(
                        name: "FK_CommittedOutputLayoutState_PlanRegistration_PlanId",
                        column: x => x.PlanId,
                        principalTable: "PlanRegistration",
                        principalColumn: "PlanId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "ExternalLocalBinding",
                columns: table => new
                {
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ExternalSourceId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    CanonicalPath = table.Column<string>(type: "TEXT", nullable: false),
                    ComparisonKey = table.Column<string>(type: "TEXT", nullable: false),
                    IsActive = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ExternalLocalBinding", x => new { x.PlanId, x.ExternalSourceId });
                    table.CheckConstraint("CK_ExternalLocalBinding_Active", "IsActive IN (0,1)");
                    table.ForeignKey(
                        name: "FK_ExternalLocalBinding_PlanRegistration_PlanId",
                        column: x => x.PlanId,
                        principalTable: "PlanRegistration",
                        principalColumn: "PlanId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "FileManagedArchiveUnitRegistration",
                columns: table => new
                {
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveUnitId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    SourceId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    LogicalUnitPath = table.Column<string>(type: "TEXT", nullable: false),
                    IdentityOrigin = table.Column<string>(type: "TEXT", nullable: false),
                    IsActive = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_FileManagedArchiveUnitRegistration", x => new { x.PlanId, x.ArchiveUnitId });
                    table.CheckConstraint("CK_FileManagedRegistration_Active", "IsActive IN (0,1)");
                    table.CheckConstraint("CK_FileManagedRegistration_Ids", "length(PlanId)=16 AND length(SourceId)=16 AND length(ArchiveUnitId)=16");
                    table.CheckConstraint("CK_FileManagedRegistration_Origin", "IdentityOrigin IN ('DIRECTIVE','LOCAL_REGISTRATION')");
                    table.ForeignKey(
                        name: "FK_FileManagedArchiveUnitRegistration_PlanRegistration_PlanId",
                        column: x => x.PlanId,
                        principalTable: "PlanRegistration",
                        principalColumn: "PlanId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "MaintenanceState",
                columns: table => new
                {
                    MaintenanceStateRowId = table.Column<long>(type: "INTEGER", nullable: false)
                        .Annotation("Sqlite:Autoincrement", true),
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveUnitId = table.Column<byte[]>(type: "BLOB", nullable: true),
                    Kind = table.Column<string>(type: "TEXT", nullable: false),
                    Status = table.Column<string>(type: "TEXT", nullable: false),
                    Detail = table.Column<string>(type: "TEXT", nullable: true),
                    UpdatedAtUtcMs = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MaintenanceState", x => x.MaintenanceStateRowId);
                    table.CheckConstraint("CK_Maintenance_Kind", "Kind IN ('HISTORY_RETENTION','OLD_CURRENT_PATH_CLEANUP','STORAGE_RELOCATION','OUTPUT_REORGANIZATION','SCHEDULE_RECONCILIATION')");
                    table.CheckConstraint("CK_Maintenance_Status", "Status IN ('PENDING','OUT_OF_SYNC','COMPLETED')");
                    table.ForeignKey(
                        name: "FK_MaintenanceState_PlanRegistration_PlanId",
                        column: x => x.PlanId,
                        principalTable: "PlanRegistration",
                        principalColumn: "PlanId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "ManagedPlanDocument",
                columns: table => new
                {
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    Revision = table.Column<long>(type: "INTEGER", nullable: false),
                    CanonicalUtf8Payload = table.Column<byte[]>(type: "BLOB", nullable: false),
                    PayloadSha256 = table.Column<byte[]>(type: "BLOB", nullable: false),
                    UpdatedAtUtcMs = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ManagedPlanDocument", x => x.PlanId);
                    table.CheckConstraint("CK_ManagedPlanDocument_Digest", "length(PayloadSha256)=32");
                    table.CheckConstraint("CK_ManagedPlanDocument_Payload", "length(CanonicalUtf8Payload)>0");
                    table.CheckConstraint("CK_ManagedPlanDocument_Revision", "Revision > 0");
                    table.ForeignKey(
                        name: "FK_ManagedPlanDocument_PlanRegistration_PlanId",
                        column: x => x.PlanId,
                        principalTable: "PlanRegistration",
                        principalColumn: "PlanId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "OutputRootLocalBinding",
                columns: table => new
                {
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    RootKind = table.Column<string>(type: "TEXT", nullable: false),
                    CanonicalPath = table.Column<string>(type: "TEXT", nullable: false),
                    ComparisonKey = table.Column<string>(type: "TEXT", nullable: false),
                    IsActive = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_OutputRootLocalBinding", x => new { x.PlanId, x.RootKind });
                    table.CheckConstraint("CK_OutputRootLocalBinding_Active", "IsActive IN (0,1)");
                    table.ForeignKey(
                        name: "FK_OutputRootLocalBinding_PlanRegistration_PlanId",
                        column: x => x.PlanId,
                        principalTable: "PlanRegistration",
                        principalColumn: "PlanId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "PublishIntent",
                columns: table => new
                {
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveUnitId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    NewArchiveVersionId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    Stage = table.Column<string>(type: "TEXT", nullable: false),
                    NewArchiveFormat = table.Column<string>(type: "TEXT", nullable: false),
                    NewArchiveSpecFingerprint = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ExpectedNewIntegritySha256 = table.Column<byte[]>(type: "BLOB", nullable: false),
                    NewLength = table.Column<long>(type: "INTEGER", nullable: false),
                    CurrentRelativePath = table.Column<string>(type: "TEXT", nullable: false),
                    OutputLayoutFingerprint = table.Column<byte[]>(type: "BLOB", nullable: false),
                    CurrentPublishedAtUtcMs = table.Column<long>(type: "INTEGER", nullable: true),
                    OldArchiveVersionId = table.Column<byte[]>(type: "BLOB", nullable: true),
                    OldArchiveFormat = table.Column<string>(type: "TEXT", nullable: true),
                    OldArchiveSpecFingerprint = table.Column<byte[]>(type: "BLOB", nullable: true),
                    OldIntegritySha256 = table.Column<byte[]>(type: "BLOB", nullable: true),
                    OldLength = table.Column<long>(type: "INTEGER", nullable: true),
                    OldPublishedAtUtcMs = table.Column<long>(type: "INTEGER", nullable: true),
                    OldCurrentRelativePath = table.Column<string>(type: "TEXT", nullable: true),
                    HistoryRelativePath = table.Column<string>(type: "TEXT", nullable: true),
                    HistoryVerifiedIntegritySha256 = table.Column<byte[]>(type: "BLOB", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PublishIntent", x => new { x.PlanId, x.ArchiveUnitId });
                    table.CheckConstraint("CK_PublishIntent_Digests", "length(NewArchiveSpecFingerprint)=32 AND length(ExpectedNewIntegritySha256)=32 AND length(OutputLayoutFingerprint)=32 AND (OldArchiveSpecFingerprint IS NULL OR length(OldArchiveSpecFingerprint)=32) AND (OldIntegritySha256 IS NULL OR length(OldIntegritySha256)=32) AND (HistoryVerifiedIntegritySha256 IS NULL OR length(HistoryVerifiedIntegritySha256)=32)");
                    table.CheckConstraint("CK_PublishIntent_Ids", "length(PlanId)=16 AND length(ArchiveUnitId)=16 AND length(NewArchiveVersionId)=16 AND (OldArchiveVersionId IS NULL OR length(OldArchiveVersionId)=16)");
                    table.CheckConstraint("CK_PublishIntent_OldFacts", "(OldArchiveVersionId IS NULL AND OldArchiveFormat IS NULL AND OldArchiveSpecFingerprint IS NULL AND OldIntegritySha256 IS NULL AND OldLength IS NULL AND OldPublishedAtUtcMs IS NULL AND OldCurrentRelativePath IS NULL AND HistoryRelativePath IS NULL AND HistoryVerifiedIntegritySha256 IS NULL) OR (OldArchiveVersionId IS NOT NULL AND OldArchiveFormat IS NOT NULL AND OldArchiveSpecFingerprint IS NOT NULL AND OldIntegritySha256 IS NOT NULL AND OldLength>=0 AND OldPublishedAtUtcMs IS NOT NULL AND OldCurrentRelativePath IS NOT NULL)");
                    table.CheckConstraint("CK_PublishIntent_Stage", "Stage IN ('PREPARED','HISTORY_CAPTURED','CURRENT_PUBLISHED','METADATA_COMMITTED')");
                    table.CheckConstraint("CK_PublishIntent_StageFacts", "(Stage='PREPARED' AND CurrentPublishedAtUtcMs IS NULL AND HistoryRelativePath IS NULL AND HistoryVerifiedIntegritySha256 IS NULL) OR (Stage='HISTORY_CAPTURED' AND CurrentPublishedAtUtcMs IS NULL AND OldArchiveVersionId IS NOT NULL AND HistoryRelativePath IS NOT NULL AND HistoryVerifiedIntegritySha256 IS NOT NULL) OR (Stage IN ('CURRENT_PUBLISHED','METADATA_COMMITTED') AND CurrentPublishedAtUtcMs IS NOT NULL AND ((OldArchiveVersionId IS NULL AND HistoryRelativePath IS NULL AND HistoryVerifiedIntegritySha256 IS NULL) OR (OldArchiveVersionId IS NOT NULL AND HistoryRelativePath IS NOT NULL AND HistoryVerifiedIntegritySha256 IS NOT NULL)))");
                    table.ForeignKey(
                        name: "FK_PublishIntent_PlanRegistration_PlanId",
                        column: x => x.PlanId,
                        principalTable: "PlanRegistration",
                        principalColumn: "PlanId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "ScheduleInstallation",
                columns: table => new
                {
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    DeviceId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    Status = table.Column<string>(type: "TEXT", nullable: false),
                    AdapterToken = table.Column<string>(type: "TEXT", nullable: true),
                    OpaqueInstallationId = table.Column<string>(type: "TEXT", nullable: true),
                    InstalledIntentDigest = table.Column<byte[]>(type: "BLOB", nullable: true),
                    UpdatedAtUtcMs = table.Column<long>(type: "INTEGER", nullable: false),
                    LastError = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_ScheduleInstallation", x => new { x.PlanId, x.DeviceId });
                    table.CheckConstraint("CK_Schedule_Digest", "InstalledIntentDigest IS NULL OR length(InstalledIntentDigest)=32");
                    table.CheckConstraint("CK_Schedule_Status", "Status IN ('NOT_INSTALLED','INSTALLED','OUT_OF_SYNC','ERROR')");
                    table.ForeignKey(
                        name: "FK_ScheduleInstallation_PlanRegistration_PlanId",
                        column: x => x.PlanId,
                        principalTable: "PlanRegistration",
                        principalColumn: "PlanId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "SecretBinding",
                columns: table => new
                {
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    SecretSlotId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ProviderToken = table.Column<string>(type: "TEXT", nullable: false),
                    OpaqueReference = table.Column<string>(type: "TEXT", nullable: false),
                    SecretRevision = table.Column<long>(type: "INTEGER", nullable: false),
                    IsActive = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SecretBinding", x => new { x.PlanId, x.SecretSlotId });
                    table.CheckConstraint("CK_SecretBinding_Active", "IsActive IN (0,1)");
                    table.CheckConstraint("CK_SecretBinding_Revision", "SecretRevision > 0");
                    table.ForeignKey(
                        name: "FK_SecretBinding_PlanRegistration_PlanId",
                        column: x => x.PlanId,
                        principalTable: "PlanRegistration",
                        principalColumn: "PlanId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "SourceLocalBinding",
                columns: table => new
                {
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    SourceId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    CanonicalPath = table.Column<string>(type: "TEXT", nullable: false),
                    ComparisonKey = table.Column<string>(type: "TEXT", nullable: false),
                    IsActive = table.Column<long>(type: "INTEGER", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SourceLocalBinding", x => new { x.PlanId, x.SourceId });
                    table.CheckConstraint("CK_SourceLocalBinding_Active", "IsActive IN (0,1)");
                    table.ForeignKey(
                        name: "FK_SourceLocalBinding_PlanRegistration_PlanId",
                        column: x => x.PlanId,
                        principalTable: "PlanRegistration",
                        principalColumn: "PlanId",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "CommittedArchiveUnitBaseline",
                columns: table => new
                {
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveUnitId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveVersionId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    FingerprintEncodingVersion = table.Column<long>(type: "INTEGER", nullable: false),
                    RulesSemanticsVersion = table.Column<long>(type: "INTEGER", nullable: false),
                    ArchiveSemanticsVersion = table.Column<long>(type: "INTEGER", nullable: false),
                    OutputPathEncodingVersion = table.Column<long>(type: "INTEGER", nullable: false),
                    EntrySetFingerprint = table.Column<byte[]>(type: "BLOB", nullable: false),
                    SelectionFingerprint = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveSpecFingerprint = table.Column<byte[]>(type: "BLOB", nullable: false),
                    RulesComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    BoundaryComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    LinkPolicyComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ExternalMappingComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    FormatComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    CompressionComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ProtectionComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ManifestComponent = table.Column<byte[]>(type: "BLOB", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CommittedArchiveUnitBaseline", x => new { x.PlanId, x.ArchiveUnitId });
                    table.CheckConstraint("CK_Baseline_Digests", "length(EntrySetFingerprint)=32 AND length(SelectionFingerprint)=32 AND length(ArchiveSpecFingerprint)=32 AND length(RulesComponent)=32 AND length(BoundaryComponent)=32 AND length(LinkPolicyComponent)=32 AND length(ExternalMappingComponent)=32 AND length(FormatComponent)=32 AND length(CompressionComponent)=32 AND length(ProtectionComponent)=32 AND length(ManifestComponent)=32");
                    table.ForeignKey(
                        name: "FK_CommittedArchiveUnitBaseline_ArchiveVersion_PlanId_ArchiveUnitId_ArchiveVersionId",
                        columns: x => new { x.PlanId, x.ArchiveUnitId, x.ArchiveVersionId },
                        principalTable: "ArchiveVersion",
                        principalColumns: new[] { "PlanId", "ArchiveUnitId", "ArchiveVersionId" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "CurrentVersion",
                columns: table => new
                {
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveUnitId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveVersionId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    CurrentRelativePath = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_CurrentVersion", x => new { x.PlanId, x.ArchiveUnitId });
                    table.ForeignKey(
                        name: "FK_CurrentVersion_ArchiveVersion_PlanId_ArchiveUnitId_ArchiveVersionId",
                        columns: x => new { x.PlanId, x.ArchiveUnitId, x.ArchiveVersionId },
                        principalTable: "ArchiveVersion",
                        principalColumns: new[] { "PlanId", "ArchiveUnitId", "ArchiveVersionId" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "HistoryVersionPlacement",
                columns: table => new
                {
                    ArchiveVersionId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveUnitId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    HistoryRelativePath = table.Column<string>(type: "TEXT", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_HistoryVersionPlacement", x => x.ArchiveVersionId);
                    table.ForeignKey(
                        name: "FK_HistoryVersionPlacement_ArchiveVersion_PlanId_ArchiveUnitId_ArchiveVersionId",
                        columns: x => new { x.PlanId, x.ArchiveUnitId, x.ArchiveVersionId },
                        principalTable: "ArchiveVersion",
                        principalColumns: new[] { "PlanId", "ArchiveUnitId", "ArchiveVersionId" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "PublishIntentBaseline",
                columns: table => new
                {
                    PlanId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveUnitId = table.Column<byte[]>(type: "BLOB", nullable: false),
                    FingerprintEncodingVersion = table.Column<long>(type: "INTEGER", nullable: false),
                    RulesSemanticsVersion = table.Column<long>(type: "INTEGER", nullable: false),
                    ArchiveSemanticsVersion = table.Column<long>(type: "INTEGER", nullable: false),
                    OutputPathEncodingVersion = table.Column<long>(type: "INTEGER", nullable: false),
                    EntrySetFingerprint = table.Column<byte[]>(type: "BLOB", nullable: false),
                    SelectionFingerprint = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ArchiveSpecFingerprint = table.Column<byte[]>(type: "BLOB", nullable: false),
                    OutputLayoutFingerprint = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ExecutionSemanticFingerprint = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ExecutionBindingFingerprint = table.Column<byte[]>(type: "BLOB", nullable: false),
                    RulesComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    BoundaryComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    LinkPolicyComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ExternalMappingComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    FormatComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    CompressionComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ProtectionComponent = table.Column<byte[]>(type: "BLOB", nullable: false),
                    ManifestComponent = table.Column<byte[]>(type: "BLOB", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PublishIntentBaseline", x => new { x.PlanId, x.ArchiveUnitId });
                    table.CheckConstraint("CK_PublishIntentBaseline_Digests", "length(EntrySetFingerprint)=32 AND length(SelectionFingerprint)=32 AND length(ArchiveSpecFingerprint)=32 AND length(RulesComponent)=32 AND length(BoundaryComponent)=32 AND length(LinkPolicyComponent)=32 AND length(ExternalMappingComponent)=32 AND length(FormatComponent)=32 AND length(CompressionComponent)=32 AND length(ProtectionComponent)=32 AND length(ManifestComponent)=32 AND length(OutputLayoutFingerprint)=32 AND length(ExecutionSemanticFingerprint)=32 AND length(ExecutionBindingFingerprint)=32");
                    table.ForeignKey(
                        name: "FK_PublishIntentBaseline_PublishIntent_PlanId_ArchiveUnitId",
                        columns: x => new { x.PlanId, x.ArchiveUnitId },
                        principalTable: "PublishIntent",
                        principalColumns: new[] { "PlanId", "ArchiveUnitId" },
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_CommittedArchiveUnitBaseline_PlanId_ArchiveUnitId_ArchiveVersionId",
                table: "CommittedArchiveUnitBaseline",
                columns: new[] { "PlanId", "ArchiveUnitId", "ArchiveVersionId" });

            migrationBuilder.CreateIndex(
                name: "IX_CurrentVersion_ArchiveVersionId",
                table: "CurrentVersion",
                column: "ArchiveVersionId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_CurrentVersion_PlanId_ArchiveUnitId_ArchiveVersionId",
                table: "CurrentVersion",
                columns: new[] { "PlanId", "ArchiveUnitId", "ArchiveVersionId" });

            migrationBuilder.CreateIndex(
                name: "IX_DatabaseMetadata_DatabaseId",
                table: "DatabaseMetadata",
                column: "DatabaseId",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_FileManagedArchiveUnitRegistration_PlanId_SourceId_LogicalUnitPath",
                table: "FileManagedArchiveUnitRegistration",
                columns: new[] { "PlanId", "SourceId", "LogicalUnitPath" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_HistoryVersionPlacement_PlanId_ArchiveUnitId_ArchiveVersionId",
                table: "HistoryVersionPlacement",
                columns: new[] { "PlanId", "ArchiveUnitId", "ArchiveVersionId" });

            migrationBuilder.CreateIndex(
                name: "IX_HistoryVersionPlacement_PlanId_HistoryRelativePath",
                table: "HistoryVersionPlacement",
                columns: new[] { "PlanId", "HistoryRelativePath" },
                unique: true);

            migrationBuilder.CreateIndex(
                name: "UX_MaintenanceState_PlanScope",
                table: "MaintenanceState",
                columns: new[] { "PlanId", "Kind" },
                unique: true,
                filter: "ArchiveUnitId IS NULL");

            migrationBuilder.CreateIndex(
                name: "UX_MaintenanceState_UnitScope",
                table: "MaintenanceState",
                columns: new[] { "PlanId", "ArchiveUnitId", "Kind" },
                unique: true,
                filter: "ArchiveUnitId IS NOT NULL");

            migrationBuilder.CreateIndex(
                name: "IX_PublishIntent_NewArchiveVersionId",
                table: "PublishIntent",
                column: "NewArchiveVersionId",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "CommittedArchiveUnitBaseline");

            migrationBuilder.DropTable(
                name: "CommittedOutputLayoutState");

            migrationBuilder.DropTable(
                name: "CurrentVersion");

            migrationBuilder.DropTable(
                name: "DatabaseMetadata");

            migrationBuilder.DropTable(
                name: "ExternalLocalBinding");

            migrationBuilder.DropTable(
                name: "FileManagedArchiveUnitRegistration");

            migrationBuilder.DropTable(
                name: "HistoryVersionPlacement");

            migrationBuilder.DropTable(
                name: "MaintenanceState");

            migrationBuilder.DropTable(
                name: "ManagedPlanDocument");

            migrationBuilder.DropTable(
                name: "OutputRootLocalBinding");

            migrationBuilder.DropTable(
                name: "PublishIntentBaseline");

            migrationBuilder.DropTable(
                name: "ScheduleInstallation");

            migrationBuilder.DropTable(
                name: "SecretBinding");

            migrationBuilder.DropTable(
                name: "SourceLocalBinding");

            migrationBuilder.DropTable(
                name: "ArchiveVersion");

            migrationBuilder.DropTable(
                name: "PublishIntent");

            migrationBuilder.DropTable(
                name: "PlanRegistration");
        }
    }
}
