<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\StowCrate.Archiving\StowCrate.Archiving.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\schemas\archive-manifest-v1.schema.json" Link="schemas\archive-manifest-v1.schema.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
